# Generated by Django 5.0.1 on 2024-01-31 18:53

import django.db.models.manager
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ELearningApp', '0011_payment'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='course',
            managers=[
                ('prod', django.db.models.manager.Manager()),
            ],
        ),
    ]
